import type { Metadata } from "next";
import { Inter, Figtree } from "next/font/google";
import "./globals.css";

export const figtree = Figtree({
  subsets: ["latin"],  // required
  weight: ["400", "500", "600", "700"], // choose the weights you need
  variable: "--font-figtree", // optional if you want to use with Tailwind
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${figtree.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
